import { defineConfig } from 'vitepress'

export default defineConfig({
  ignoreDeadLinks: true,
  base: '/azurelocal-nutanix-migration/',
  title: "Nutanix to Azure Local Migration",
  description: "Governed centrally by HCS Platform Engineering standards",
  themeConfig: {
    logo: '/assets/images/azurelocal-nutanix-migration-icon.svg',
    nav: [{"link":"/","text":"Home"},{"items":[{"link":"/overview/index","text":"Introduction"},{"link":"/overview/migration-phases","text":"Migration Phases"},{"link":"/overview/tool-comparison","text":"Tool Comparison"}],"text":"Overview"},{"items":[{"link":"/scenarios/index","text":"Choose Your Path"},{"items":[{"link":"/scenarios/01-veeam/index","text":"Overview"},{"link":"/scenarios/01-veeam/prerequisites","text":"Prerequisites"},{"link":"/scenarios/01-veeam/architecture","text":"Architecture"},{"link":"/scenarios/01-veeam/runbook","text":"Runbook"},{"link":"/scenarios/01-veeam/validation","text":"Validation & Checklist"}],"text":"Veeam Migration Path"},{"items":[{"link":"/scenarios/02-hycu/index","text":"Overview"},{"link":"/scenarios/02-hycu/prerequisites","text":"Prerequisites"},{"link":"/scenarios/02-hycu/architecture","text":"Architecture"},{"link":"/scenarios/02-hycu/runbook","text":"Runbook"},{"link":"/scenarios/02-hycu/validation","text":"Validation & Checklist"}],"text":"HYCU Migration Path"},{"items":[{"link":"/scenarios/03-commvault/index","text":"Overview"},{"link":"/scenarios/03-commvault/prerequisites","text":"Prerequisites"},{"link":"/scenarios/03-commvault/architecture","text":"Architecture"},{"link":"/scenarios/03-commvault/runbook","text":"Runbook"},{"link":"/scenarios/03-commvault/validation","text":"Validation & Checklist"}],"text":"Commvault Migration Path"},{"items":[{"link":"/scenarios/04-deploy-first/index","text":"Overview"},{"link":"/scenarios/04-deploy-first/prerequisites","text":"Prerequisites"},{"link":"/scenarios/04-deploy-first/architecture","text":"Architecture"},{"link":"/scenarios/04-deploy-first/runbook","text":"Runbook"},{"link":"/scenarios/04-deploy-first/validation","text":"Validation & Checklist"}],"text":"Deploy-First Migration (Carbonite)"},{"items":[{"link":"/scenarios/05-alternative-migration-methods/index","text":"Overview"},{"link":"/scenarios/05-alternative-migration-methods/prerequisites","text":"Prerequisites"},{"link":"/scenarios/05-alternative-migration-methods/runbook","text":"Runbook"},{"link":"/scenarios/05-alternative-migration-methods/validation","text":"Validation & Checklist"}],"text":"Alternative Migration Methods"}],"text":"Migration Scenarios"},{"items":[{"link":"/poc/index","text":"Overview"},{"link":"/poc/test-matrix","text":"Test Matrix"},{"link":"/poc/timeline","text":"Timeline & Decisions"}],"text":"Proof of Concept"},{"link":"/diagrams/index","text":"Diagrams"},{"items":[{"link":"/reference/tool-comparison-matrix","text":"Tool Comparison Matrix"},{"link":"/reference/network-requirements","text":"Network Requirements"},{"link":"/reference/ip-mapping-template","text":"IP Mapping Template"},{"link":"/reference/glossary","text":"Glossary"}],"text":"Reference"},{"link":"/contributing","text":"Contributing"}],
    sidebar: [{"link":"/","text":"Home"},{"text":"Overview","items":[{"link":"/overview/index","text":"Introduction"},{"link":"/overview/migration-phases","text":"Migration Phases"},{"link":"/overview/tool-comparison","text":"Tool Comparison"}],"collapsed":false},{"text":"Migration Scenarios","items":[{"link":"/scenarios/index","text":"Choose Your Path"},{"text":"Veeam Migration Path","items":[{"link":"/scenarios/01-veeam/index","text":"Overview"},{"link":"/scenarios/01-veeam/prerequisites","text":"Prerequisites"},{"link":"/scenarios/01-veeam/architecture","text":"Architecture"},{"link":"/scenarios/01-veeam/runbook","text":"Runbook"},{"link":"/scenarios/01-veeam/validation","text":"Validation & Checklist"}],"collapsed":false},{"text":"HYCU Migration Path","items":[{"link":"/scenarios/02-hycu/index","text":"Overview"},{"link":"/scenarios/02-hycu/prerequisites","text":"Prerequisites"},{"link":"/scenarios/02-hycu/architecture","text":"Architecture"},{"link":"/scenarios/02-hycu/runbook","text":"Runbook"},{"link":"/scenarios/02-hycu/validation","text":"Validation & Checklist"}],"collapsed":false},{"text":"Commvault Migration Path","items":[{"link":"/scenarios/03-commvault/index","text":"Overview"},{"link":"/scenarios/03-commvault/prerequisites","text":"Prerequisites"},{"link":"/scenarios/03-commvault/architecture","text":"Architecture"},{"link":"/scenarios/03-commvault/runbook","text":"Runbook"},{"link":"/scenarios/03-commvault/validation","text":"Validation & Checklist"}],"collapsed":false},{"text":"Deploy-First Migration (Carbonite)","items":[{"link":"/scenarios/04-deploy-first/index","text":"Overview"},{"link":"/scenarios/04-deploy-first/prerequisites","text":"Prerequisites"},{"link":"/scenarios/04-deploy-first/architecture","text":"Architecture"},{"link":"/scenarios/04-deploy-first/runbook","text":"Runbook"},{"link":"/scenarios/04-deploy-first/validation","text":"Validation & Checklist"}],"collapsed":false},{"text":"Alternative Migration Methods","items":[{"link":"/scenarios/05-alternative-migration-methods/index","text":"Overview"},{"link":"/scenarios/05-alternative-migration-methods/prerequisites","text":"Prerequisites"},{"link":"/scenarios/05-alternative-migration-methods/runbook","text":"Runbook"},{"link":"/scenarios/05-alternative-migration-methods/validation","text":"Validation & Checklist"}],"collapsed":false}],"collapsed":false},{"text":"Proof of Concept","items":[{"link":"/poc/index","text":"Overview"},{"link":"/poc/test-matrix","text":"Test Matrix"},{"link":"/poc/timeline","text":"Timeline & Decisions"}],"collapsed":false},{"link":"/diagrams/index","text":"Diagrams"},{"text":"Reference","items":[{"link":"/reference/tool-comparison-matrix","text":"Tool Comparison Matrix"},{"link":"/reference/network-requirements","text":"Network Requirements"},{"link":"/reference/ip-mapping-template","text":"IP Mapping Template"},{"link":"/reference/glossary","text":"Glossary"}],"collapsed":false},{"link":"/contributing","text":"Contributing"}],
    socialLinks: [
      { icon: 'github', link: 'https://github.com/AzureLocal/azurelocal-nutanix-migration' }
    ],
    footer: {
      message: 'Released under the MIT License.',
      copyright: 'Copyright © Hybrid Cloud Solutions & AzureLocal'
    }
  }
})




